### ISSUE TITLE
 Is there a way to make the "mask" show up in English? 

### ISSUE THREAD

**Issue by playhousehosting** [Yidadaa/ChatGPT-Next-Web#1367]
Is it possible to change the "mask" to show English?

**Comment by darth-pika-hu** [comment]
Manually add English Masks.

**Comment by Yidadaa** [comment]
Due to recent busy schedules, there are no built-in masks for languages other than Chinese. We welcome the submission of a PR to add more language masks. You just need to modify the following code:

https://github.com/Yidadaa/ChatGPT-Next-Web/blob/e9df58709ed9896c367a283a05b50a3a878c1d72/app/masks/en.ts#L3
