### ISSUE TITLE
[Feature] 使用glm2部署的openai接口服务，自定义地址后返回"Failed to fetch"

### ISSUE THREAD

**Issue by likunpm** [Yidadaa/ChatGPT-Next-Web#2240]
rt
如果使用自定义的api服务，可以不可以让用户自己勾选校验不校验账单啊

**Comment by Yidadaa** [comment]
账单不会影响你使用，升级 glm2 的代码到最新。

**Comment by yinjianjie** [comment]
楼主问题解决了吗

**Comment by yinjianjie** [comment]
No未来可期------------------ 原始邮件 ------------------发件人: Issues-translate-bot  ***@***.***>发送时间: 2023年7月5日 18:26收件人: Yidadaa/ChatGPT-Next-Web ***@***.***>抄送: Jeff ***@***.***>, Comment ***@***.***>主题: Re: [Yidadaa/ChatGPT-Next-Web] [Feature] 使用glm2部署的openai接口服务，自定义地址后返回"Failed to fetch" (Issue #2240)

Bot detected the issue body's language is not English, translate it automatically.


Has the landlord problem been solved?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/Yidadaa/ChatGPT-Next-Web/issues/2240#issuecomment-1621476823",
"url": "https://github.com/Yidadaa/ChatGPT-Next-Web/issues/2240#issuecomment-1621476823",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
