### ISSUE TITLE
[Feature] Account system

### ISSUE THREAD

**Issue by Philantrop** [Yidadaa/ChatGPT-Next-Web#2299]
I'm using a lot of different devices and environments, e. g. my desktop PC, a laptop, mobile devices. I have to configure my preferred settings, prompts, masks, and so on, on every single device.
I also have a family who are also using a lot of devices each. The effort to configure my own devices is already at painful levels. Configuring those of my tech-challenged family members - a nightmare.

An account system, as previously asked for in issue #28 (and others) and recently discussed in discussion #2207, and, thus, probably a popular feature to have, would alleviate much of the pains I described.
It would also be a differentiating factor, raising ChatGPT-Next-Web even further above its competitors. 

In the first step, such an account system would likely be ChatGPT-Next-Web-local, i. e. a simple initial implementation that would allow for creating an account, logging into any such account, changing the password for such an account and storing preferences in relation to such an account.

Ideally, such an account system would ultimately be pluggable, e. g. use configurable backends (e. g. LDAP) or external authentication methods (e. g. OIDC). It would possibly also make use of pluggable backends for storage, e. g. a database like sqlite for minimal installations or PostgreSQL for regular ones.

**Comment by imabutahersiddik** [comment]
I understand the need for an account system to simplify the configuration process across multiple devices and environments. It would indeed be a valuable feature for users who frequently switch between devices and for those who manage multiple devices for their family members. An account system would centralize settings, prompts, and masks, making it easier to maintain a consistent experience across devices.

The suggested approach of starting with a local implementation and then expanding to support configurable backends and external authentication methods is a reasonable strategy. This would allow users to create accounts, log in, and manage their preferences within the ChatGPT-Next-Web application. Additionally, providing pluggable backends for storage would offer flexibility in choosing the appropriate database solution based on the installation requirements.

Overall, implementing an account system would enhance user experience and set ChatGPT-Next-Web apart from its competitors.

**Comment by Pnut-GGG** [comment]
I have had a similar experience.

**Comment by Yidadaa** [comment]
I must reiterate that this project will not introduce any native database support. Introducing any database support would make the deployment of the project more challenging, which contradicts the original intention behind creating this project.

Many similar open-source projects tend to introduce unnecessary features as the codebase expands, ultimately making the configuration and usage of the project a mess. I believe we should focus on how to improve the chat experience.

I understand the necessity of the requirements you have raised, and I am currently discussing with the community to seek a better solution. However, the account system is not within the scope of consideration.

Here are some planned features:
- #920 For chat log synchronization, we plan to introduce a synchronization mechanism based on webdav, which can synchronize chat logs, settings, masks, prompts, and other data.
- For built-in masks, prompts, default configurations, etc., we plan to add a "subscription source" mechanism, where users can subscribe to these data from any HTTP link to keep their configurations in sync.

In addition, this project uses GitHub Actions as a synchronization mechanism. If you fork this project and enable GitHub Actions, it will regularly synchronize with the upstream code. So, if you have outstanding personal customization ideas, it is recommended to try implementing them in your own downstream repository first, instead of requesting the main repository to add the feature. When your feature implementation is mature enough, you can submit a pull request. The requests in the pull request list will be considered based on the opinions of the community.

This project is being used by thousands of people, and we must be very cautious in adding new features. Of course, we would like to incorporate useful new features, but if that makes the project more complex and difficult to understand, it would be a trade-off that is not worth it.

Thank you once again for your feedback.

**Comment by Philantrop** [comment]
I'm not a developer. Sadly, there are currently no other projects as advanced as this one out there. I see our ideas about what's more important - ease of deployment versus features - are on polar opposites of the scale. 
I'll bow out.
