### ISSUE TITLE
[Feature] Desktop suggestions

### ISSUE THREAD

**Issue by AsafMah** [Yidadaa/ChatGPT-Next-Web#2310]
**Is your feature request related to a problem? Please describe.**

The desktop portion is currently very bare-bones.
I have some suggestions on features it could have. 
I might be able to help contribute to them myself.

**Describe the solution you'd like**

- Global hotkeys, to:
   - Open the app (popup)
   - Add to chat from clipboard
   - Paste from chat to clipboard
   - Etc..
   
- Minimize in tray when closed (windows)
- Some sort of popup/mini window to ask quick questions, in combination with the hotkeys (like opening a small translate window for example)

**Describe alternatives you've considered**
Some of these are available in other chatgpt desktop programs,

**Additional context**

**Comment by Yidadaa** [comment]
Thank you for the suggestion. In the early stages of this project, it was primarily a web-based project. Client support was only officially introduced in version 2.8, so many client-specific features are still lacking. I would like to clarify that the desktop client is not the primary focus of this project. Due to limited availability of the project maintainers, our priority lies in addressing the functionality items outlined in the roadmap. Client-specific features are of lower priority.
