### ISSUE TITLE
[Bug] What is defference btw user / assistant / system

### ISSUE THREAD

**Issue by johnfelipe** [Yidadaa/ChatGPT-Next-Web#2394]
Im recent latest deploy in vercel with latest pull few hour ago and chat is not responding with a good accuracy, pls view this video

https://github.com/Yidadaa/ChatGPT-Next-Web/assets/428820/7670cea4-39c1-4c08-b7aa-8eabc7d8315d

how can solve that issue

**Comment by Yidadaa** [comment]
For human messages, use `user`,
For bot's responses, use `assistant`,
For system level information / external knowledge, use `system`.

You should learn `prompt engineering`, google it or find some videos on Youtube.

**Comment by johnfelipe** [comment]
But my question may be not works
If u see video that levels not works
I ask question user level and not answer like contextual information, do u get me know?

**Comment by Yidadaa** [comment]
I understand your point. I meant that the effectiveness of chatgpt's responses is highly dependent on the quality of the contextual prompts you provide. "How to set high-quality prompts" is an important topic in prompt engineering. The issue you encountered is that chatgpt is unable to follow your intended instructions effectively. Based on the content of your video, it seems that the quality of your contextual prompts is poor. However, I am unable to understand the language used in your video, so I cannot provide specific targeted improvements. That's why I suggested you to study prompt engineering systematically.

**Comment by johnfelipe** [comment]
@Yidadaa where can o send u Json skin file translated to English privately:

![Screenshot_2023-07-16-04-46-28-29_572064f74bd5f9fa804b05334aa4f912](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/428820/0921d8d2-3cc7-4014-97f3-fbd6f06a738c)

I request that to in discord channel

**Comment by johnfelipe** [comment]
@Yidadaa i send you to your email json private file, pls take a look
