### ISSUE TITLE
[Bug] request body缺少參數max_tokens

### ISSUE THREAD

**Issue by zhzLuke96** [Yidadaa/ChatGPT-Next-Web#3056]
**Describe the bug**
看起來發送請求的時候沒有帶上max_tokens參數，配置了也沒用

導致一個問題，本地運行的 llama_cpp_server 默認max_tokens是16...所以用不了llama_cpp_server啓動的服務，只會生產16個token就出發服務器截斷...

**To Reproduce**
發起任意聊天即可復現

**Expected behavior**
應該在請求參數中傳遞max_tokens

**Desktop (please complete the following information):**
 - OS: windows 10
 - version: v2.9.9

**Additional Logs**
大概看了下源碼好像是這裏的問題

https://github.com/Yidadaa/ChatGPT-Next-Web/blob/cc565cf57ebedc6d59483e37b7633349426ff510/app/client/platforms/openai.ts#L65-L73

沒有傳遞max_tokens😂

**一個相關issue**
https://github.com/Yidadaa/ChatGPT-Next-Web/issues/2857

雖然那個issue已經關閉了，但是估計是同樣的問題

**Comment by H0llyW00dzZ** [comment]
yeah its missing `max_tokens` without `max_tokens` it just depends tokens from user's inputs

now it fixed depends of global config
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/585e04ba-2931-40ab-86da-e869da760e82)
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/01bbe30a-4ec9-46fa-8e8d-354ec88aaecd)

**Comment by H0llyW00dzZ** [comment]
additional screenshot

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/ce1f73e6-d60e-4394-88b0-e9151e088e3a)

**Comment by H0llyW00dzZ** [comment]
additional note
in this pr `Feat ChatGPTApi` #3060  when max token's  (eg you set 4000 max tokens in settings) doesn't match for a length from users request

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/08346ae7-d726-4b52-a35c-7478373f1da9)


so I recommended set is 2000 as default because its length and it doesn't break any memory prompt(aka summarize) or masks

**Comment by Yidadaa** [comment]
故意的，这个参数在 chatgpt 场景下没用，反而会引起很多报错，我建议你直接修改 llama_server 的代码，把默认 max_tokens 限制去掉。
