### ISSUE TITLE
[Bug] ChatGPT-Next-Web本身的错误提示没有被过滤，别当做上下文提交给了OpenAI

### ISSUE THREAD

**Issue by tiyee** [Yidadaa/ChatGPT-Next-Web#3064]
**Describe the bug**
ChatGPT是没有上下文功能的，每次内容交互都是独立的。为了保持上下文连贯。所有的客户端，都会把历史消息以assistant的角色，发给ChatGPT。当然，大多数客户端都会限制内容大小，避免无限膨胀。

但ChatGPT-Next-Web本身的错误提示也是交互内容，也会被当做上下文内容以assistant角色提交，不仅干扰了对话内容，也白白浪费tokens费用。

当然，这也有用户使用的问题，因为遇到错误后应该新开一次对话而不是继续原有对话。但ChatGPT-Next-Web过滤下这些内容，或者给出提示建议用户新开窗口就更好了。

**Comment by H0llyW00dzZ** [comment]
`ChatGPT has no context function, and each content interaction is independent. To keep the context coherent. All clients will send historical messages to ChatGPT in the role of assistant. Of course, most clients will limit the content size to avoid unlimited bloat.`  there is option called masks

also for the content can't think bug because that's how summarize work to generate `memory prompt` and `tittle topics`

here is example when summarize module doing summarize of my module of `text moderations`

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/10afabf3-1193-4eba-8a41-f831cfc4fd8e)
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/cb02e913-19b8-45fc-b89b-343de8b81321)
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/4b8aff47-2b43-4355-b74b-b1c9eb741460)

simply if you want filter content `eg error content` you can just deleted a messages in chats

**Comment by Yidadaa** [comment]
错误内容已经被过滤过了。
