### ISSUE TITLE
[Feature] Function calling implementation

### ISSUE THREAD

**Issue by ograycode** [Yidadaa/ChatGPT-Next-Web#3072]
I've implemented a way to interact with [openai function calling](https://platform.openai.com/docs/guides/gpt/function-calling) that goes like this:

1. Functions are attached to the openai api call as described in the documentation.
2. If a function call is returned, the name and arguments are part of the content displayed in the new assistant chat message.
3. A "Play" button is displayed in the chat options (in the same area as "retry") if it is a function call.
4. If the "Play" button is pressed
   * the function is called in the browser and the results appear as a new assistant chat message.
   * the function results are passed as messages to openai for interpretation and displayed as a new assistant chat message

This allows users to implement their own functions to be called, and provides for a pattern to have a server execute the function call in the future.

Let me know if this is a good approach and I can submit a PR in the next couple of days.

This is closely related to #165

**Comment by H0llyW00dzZ** [comment]
yes go ahead

**Comment by Yidadaa** [comment]
I need to point out that I'm doing a huge refactor and the code structure will change dramatically in the near future, please keep an eye on this: #2603

**Comment by H0llyW00dzZ** [comment]
@Yidadaa may you need refactor this for client app in tauri
https://github.com/Yidadaa/ChatGPT-Next-Web/blob/client/app/api/cors/%5B...path%5D/route.ts#L3C1-L3C1

when used runtime `nodejs` it can't use another tauri api because keep getting this error `Error: Page "/api/cors/[...path]" is missing "generateStaticParams()" so it cannot be used with "output: export" config.` when building

**Comment by Yidadaa** [comment]
#3217
