### ISSUE TITLE
Upload Images[Feature] 

### ISSUE THREAD

**Issue by zhuzaiBro** [Yidadaa/ChatGPT-Next-Web#3100]
> can I upload Images to chat-gpt

**Comment by H0llyW00dzZ** [comment]
this one must use own external storage I think such as sync feature
(in scenario) : 
not sure if its good for adding this feature, because of CORS Policy. (eg you can't export the messages as image in exporter page)
because after image is uploaded in external storage then AI Embedding it with functional calling.

**Comment by Yidadaa** [comment]
No, OpenAI does not have the capability to open this
