### ISSUE TITLE
使用3.5，然后报错配额不足，怎么办？[使用问题] 

### ISSUE THREAD

**Issue by BinbinbinDashen** [Yidadaa/ChatGPT-Next-Web#3106]
{
  "error": {
    "message": "You exceeded your current quota, please check your plan and billing details.",
    "type": "insufficient_quota",
    "param": null,
    "code": "insufficient_quota"
  }
}

**Comment by H0llyW00dzZ** [comment]
add funds in https://platform.openai.com/account/billing/overview

**Comment by Wangggym** [comment]
<img width="465" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/26135370/df010a43-812d-4333-a9e3-f56bad792e2d">
<img width="524" alt="image" src="https://github.com/Yidadaa/ChatGPT-Next-Web/assets/26135370/8eb97155-5f9e-4f6e-9cb2-75e9dc41e67c">

How can I make a credit card?  It looks like there is not support.

**Comment by H0llyW00dzZ** [comment]
you need someone (outside china) such as friends,or family I think for add funds.
and there is other way, buy a virtual credit card (prepaid cards) which already have balance on it (eg $25 virtual credit card).
since stripe support virtual credit card (prepaid cards)

**Comment by Wangggym** [comment]
thanks, it's useful. @H0llyW00dzZ

**Comment by Agilan989** [comment]
Thanks for information.. but any other way to get the info??

**Comment by H0llyW00dzZ** [comment]
here is example of information to buy virtual credit card 
eg : https://www.bitrefill.com/blog/buy-virtual-credit-card-with-bitcoin-or-crypto/
and can find in this one (which support china) for buying crypto such as bitcoin
https://paxful.com/

Also I used a virtual credit card to add funds to OpenAI. However, my virtual credit card is different. I generated it from my local bank because in my country, most banks can easily create virtual credit cards.
each time when add fund with virtual credit card : 

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/255a45c7-7e30-47a0-92db-da574a77d381)

**Comment by Agilan989** [comment]
Need to clarify that I can't make transactions.. developers was blocked me download my binance app from app gallery.. than how come I made payments to transfer all stuck on binance..

**Comment by H0llyW00dzZ** [comment]
idk tbh, might your country is not supported.

**Comment by Wangggym** [comment]
@H0llyW00dzZ I found out that China Merchants Bank also has Visa credit card support.

**Comment by H0llyW00dzZ** [comment]
@Wangggym you can add funds now ?

**Comment by Wangggym** [comment]
@H0llyW00dzZ My credit card is still on the way, I'm not sure if it supports the China region. Let me give it a try.

**Comment by Yidadaa** [comment]
中国的用户可以考虑使用：https://api.nextweb.fun
