### ISSUE TITLE
Use Avatars Instead of Emojis for User Icons

### ISSUE THREAD

**Issue by Botuns** [Yidadaa/ChatGPT-Next-Web#3120]
I believe it would be more effective to use avatars instead of emojis for representing user icons. 
**Avatars can provide a more personal and unique representation of users, which could enhance user engagement and interaction within the platform.**

This is just a suggestion, and I'd love to hear what others think about this idea. Thank you for considering my input!

**Comment by GOvEy1nw** [comment]
Yea it'd be great if 'profile pics' were an optional feature. I enjoy the emojis for sure, but I think profile pics would feel more trustworthy/professional.

Granted, I understand it'd require some changes to the UI as the current emojis are only a few pixels in size.

If that was to take a while, perhaps a nice interim alternative could be to have the option to pick from an icon library instead, such as font awesome etc. There's generally a wider range of icons and because they're 'flat' in design and only single coloured, they'll still give that 'trustworthy'/'professional' feel a bit more than emojis.

**Comment by Yidadaa** [comment]
If you have these requirements, you can achieve them by modifying the code yourself.
