### ISSUE TITLE
[Bug]希望作者解决下CUSTOM_MODELS docker环境变量不生效的问题！！！

### ISSUE THREAD

**Issue by shehuiwojiege** [Yidadaa/ChatGPT-Next-Web#3414]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Deployment**
- [ ] Docker
- [ ] Vercel
- [ ] Server

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional Logs**
Add any logs about the problem here.

**Comment by krwu** [comment]
+1，使用了 `CUSTOM_MODELS=-all,+gpt-3.5-turbo,+gpt-4` 还是列出所有的模型。

**Comment by twelife001** [comment]
+1 我也是 `CUSTOM_MODELS="-all,+gpt-3.5-turbo,+gpt-4-1106-preview=gpt-4-turbo"`
![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/132798272/df271e40-834c-4e78-a77d-e6b3975f4055)

**Comment by H0llyW00dzZ** [comment]
it's because haven't released yet the bug is already fixed
related to this pr: 

fix(CUSTOM_MODELS):#3349 Dependency chatStore otherwise the session a… #3356

in vercel/web deployment already fixed

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/b39be579-d56c-4d64-b07f-e6380498addf)
