### ISSUE TITLE
[Bug] 使用面具GitHub Copilot时，其模型会自动选择GPT-4，设置中的无效，且切换也无效。导致费用严重超预期。

### ISSUE THREAD

**Issue by xeastsun** [Yidadaa/ChatGPT-Next-Web#3463]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Deployment**
- [ ] Docker
- [ ] Vercel
- [ ] Server

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional Logs**
Add any logs about the problem here.

**Comment by H0llyW00dzZ** [comment]
you can changed it manually

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/5ce789a9-8526-4cbd-8bb7-212355866add)

or changed it by clicking this a icon bots

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/7bc4e7f7-9bd0-4613-a3a7-d431555ad90f)


tested working fine:

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/88d6e274-8ad5-4aae-92b4-8ef867e29a40)

**Comment by xeastsun** [comment]
感谢您的回复，按照您所说的操作步骤，是没有问题的。但在右侧总设置中切换模型版本，目前测试的，GitHub Copilot不会响应切换，而其他的面具则没有问题。如下：
![Snipaste_2023-12-06_08-05-24](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/127654649/42ea4b96-3106-4962-be5f-4ba256b0742a)
谢谢！

**Comment by H0llyW00dzZ** [comment]
bruh this not a bug or something that you thinking
look this when you disable a gpt-4 in env it will automated switch to other models which is available

https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/19a49e3c-59a1-4700-b317-08379068089c

also in setting are just add this (if don't want set gpt-4 disable in env, because it will disable for all gpt-4)

![image](https://github.com/Yidadaa/ChatGPT-Next-Web/assets/17626300/960ce3b5-59c3-49c5-8d2f-03c33a62f5bf)
