### ISSUE TITLE
plugins integration

### ISSUE THREAD

**Issue by Lionardo** [Yidadaa/ChatGPT-Next-Web#763]
**Is your feature request related to a problem? Please describe.**
implement chat gptplugin

**Describe the solution you'd like**
use our simple 1 click service

hej @Yidadaa  love your chatgpt project!👏
How about integrating getitAI's open Plugin Store for easy plugin installs? (https://www.getit.ai/gpt-plugins) Let's chat for 15 mins: https://calendly.com/d/z4j-cb5-h2y/getitai-devs

**Comment by Yidadaa** [comment]
Awesome work! Do you have any video tutorials on how to use it?

**Comment by seshubonam** [comment]
+1  

@Lionardo could you describe how to connect pkugins for next-web-ui, an example or PR, so we can build on top and extend capabilities

**Comment by Yidadaa** [comment]
hi @Lionardo , thanks for your work again, but recent i found it seems impossible to use the official openai plugins in this project, because all of those plugins have limited the request by CORS policy, which makes it impossible to access plugins from domains except `openai.com`.

Do you have any ideas about this?

**Comment by digi604** [comment]
you could use a proxy to handle this problems

**Comment by Yidadaa** [comment]
@digi604 Good idea, thanks bro.

**Comment by Yidadaa** [comment]
#165
